<?php
    function comment_buddy_menu() {
        $items = array();
        $items['comment_buddy_success'] = array(
            'title' => 'Update comment',
            'page callback' => 'comment_function',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function comment_buddy_comment_update() {
        drupal_set_message("Hi there!");
    }

    function comment_buddy_comment_insert() {
        drupal_set_message("Hi there!");
    }

    function comment_buddy_comment_delete() {
        drupal_set_message("Hi there!");
    }
